apiVersion: v1
kind: Service
metadata:
  name: gpu-webhook-validator-service
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: gpu-webhook-validator-certs
  labels:
    app: gpu-webhook-validator
spec:
  ports:
    - port: 8443
      targetPort: 8443
      name: https
  selector:
    app: gpu-webhook-validator
