apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: gpu-webhook-validator
webhooks:
  - name: <route>.apps.dsri2.unimaas.nl  # Use the route URL here
    clientConfig:
      service:
        name: gpu-webhook-validator-service
        namespace: <namespace>  # Make sure to match the namespace
        path: /validate
      caBundle: <base64_encoded_ca_cert>  # oc get configmap -n <namespace> <configMap> -o jsonpath='{.data.service-ca\.crt}' | base64 -w0
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"
    admissionReviewVersions: ["v1"]
    sideEffects: None
